import * as utils from "@/app/app/utils/utils"
import { create } from "zustand"
import { useMessagesStore } from "./messages"

export const useCurrents = create<utils.Currents>((set) => ({
    channel: null,
    server: null,
    exploreboxmode: null,
    user: null,
    contextmenu: { shown: false, x: 0, y: 0, currentID: '', currentObject: null, includes: [], },
    contextmenumode: null,
    friendsdiv: { status: "online", visible: true },
    directmessage: null,
    setting: null,
    vc: null,
    voicechatopen: false,
    tooltip: { position: { left: 0, top: 0 }, ref: null, text: "", textColor: "#F0F7EE", visible: false },
    settingsMode: 'UserApp',
    userFetching: false,
    BgBlurV: false,
    ExploreBoxV: false,
    confirmationMenu: false,
    confirmationMenuText: "",
    confirmationMenuRetypeText: undefined,
    settingsDivV: false,
    SideBoxChannelsV: false,
    Categories: [],
    ServerUsersDivV: false,
    settingsObject: null,
    userVariables: null,
    liveikitRoom: '',
    livekitShown: false,
    liveKitParticipant: null,
    fullScreenVideo: null,
    fsvReturnFunction: null,
    fsvIsMirrored: true,
    isChannelLoading: false,
    helpmenuShown: false,
    messageboxRef: null,
    messageBoxSavedSelection: {start: 0, end: 0},
    setTextWritten: () => {},
    setsetTextWritten: (setTextWritten: (string: string) => void) => {set({setTextWritten})},
    setmessageBoxSavedSelection: (messageBoxSavedSelection: {start: number, end: number}) => {set({messageBoxSavedSelection})},
    setmessageBoxRef: (messageboxRef) => { set({messageboxRef})},
    sethelpmenuShown: (helpmenuShown) => { set({helpmenuShown})},
    setisChannelLoading: (isChannelLoading) => { set({isChannelLoading})},
    setFsvIsMirrored: (fsvIsMirrored) => { set({fsvIsMirrored})},
    setFsvReturnFunction: (fsvReturnFunction) => { set({fsvReturnFunction})},
    setFullScreenVideo: (fullScreenVideo) => {set({ fullScreenVideo })},
    setLiveKitParticipant: (participant) => { set({ liveKitParticipant: participant }) },
    setLivekitShown: (livekitShown) => { set({ livekitShown }) },
    setLiveikitRoom: (room) => { set({ liveikitRoom: room }) },
    setUserVariables: (userVariables) => { set({ userVariables }) },
    setContextMenuIncludes: (includes) => { set((state) => ({contextmenu: { ...state.contextmenu, includes}}))},
    setSettingsObject: (settingsObject) => { set({ settingsObject }) },
    setServerUsersDivV: (ServerUsersDivV) => { set({ ServerUsersDivV }) },
    onClickAppIcon: () => {
        set((state) => ({
            SideBoxChannelsV: false, channel: null,
            server: null, Categories: [],
            directmessage: null, friendsdiv: { ...state.friendsdiv, visible: true },
            ServerUsersDivV: false, settingsDivV: false,
        }));

        useMessagesStore.getState().setMessages([]);
    },
    setCategories: (categories => { set({ Categories: categories }) }),
    setSideBoxChannelsV: (SideBoxChannelsV) => { set({ SideBoxChannelsV }) },
    setSettingsDivV: (settingDivV) => { set({ settingsDivV: settingDivV }) },
    setconfirmationMenuRetypeText: (confirmationMenuRetypeText) => { set({ confirmationMenuRetypeText }) },
    confirmationMenuCallback: (() => { }),
    setconfirmationMenuCallback: (confirmationMenuCallback) => { set({ confirmationMenuCallback }) },
    setConfirmationMenuText: (confirmationMenuText) => { set({ confirmationMenuText }) },
    setConfirmationMenu: (confirmationMenu) => { set({ confirmationMenu }) },
    setBgBlurV: (BgBlurV) => { set({ BgBlurV }) },
    setExploreBoxV: (ExploreBoxV) => { set({ ExploreBoxV }) },
    setUserFetching: (userFetching) => { set({ userFetching }) },
    setChannel: (channel) => { set({ channel }) },
    setServer: (server) => { set({ server }) },
    setExploreBoxMode: (exploreboxmode) => { set({ exploreboxmode }) },
    setUser: (user) => { set({ user }) },
    setContextMenuShown: (shown) => { set((state) => ({ contextmenu: { ...state.contextmenu, shown } })) },
    setContextMenuXY: (x, y) => { set((state) => ({ contextmenu: { ...state.contextmenu, x, y } })) },
    setContextMenuID: (currentID) => { set((state) => ({ contextmenu: { ...state.contextmenu, currentID } })) },
    setFriendsDivV: (visible) => { set((state) => ({ friendsdiv: { ...state.friendsdiv, visible } })) },
    setFriendsDivState: (status) => { set((state) => ({ friendsdiv: { ...state.friendsdiv, status } })) },
    setDirectMessage: (directmessage) => { set({ directmessage }) },
    setSetting: (setting) => { set({ setting }) },
    setVC: (vc) => { set({ vc }) },
    setVCOpen: (voicechatopen) => { set({ voicechatopen }) },
    setTooltipPosition: (left, top) => { set((state) => ({ tooltip: { ...state.tooltip, position: { left, top } } })) },
    setSettingsMode: (settingsMode) => { set({ settingsMode }) },
    setContextMenuMode: (contextmenumode) => { set({ contextmenumode }) },
    setVCUsers: (members) => { set((state) => ({ vc: { ...state.vc, members, channelId: state.vc?.channelId || '', serverId: state.vc?.serverId || null, createdAt: state.vc?.createdAt || new Date() } })) },
    setTooltipText: (text) => { set((state) => ({ tooltip: { ...state.tooltip, text } })) },
    setTooltipTextColor: (textColor) => { set((state) => ({ tooltip: { ...state.tooltip, textColor } })) },
    setTooltipRef: (ref) => { set((state) => ({ tooltip: { ...state.tooltip, ref } })) },
    setTooltipV: (visible) => { set((state) => ({ tooltip: { ...state.tooltip, visible } })) },
    addUserServer: (server) => { set((state) => { if (state.user) { return ({ ...state, user: { ...state.user, servers: [...state.user.servers, server] } }); } else { console.log("Couldn't set state."); return state; } }) },
    deleteUserServer: (server) => { set((state) => { if (state.user) { return ({ ...state, user: { ...state.user, servers: state.user.servers.filter(x => x !== server) } }); } else { console.log("Couldn't set state."); return state; } }) },
    setUserServers: (servers) => { set((state) => { if (state.user) { return ({ user: { ...state.user, servers: servers } }); } else { console.log("Couldn't set state."); return state; } }) },
    setContextMenuObject: (object) => { set((state) => ({ contextmenu: { ...state.contextmenu, currentObject: object } })) },
}))